[package]
name = "distributed-kvstore"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.13.0"
tokio = { version = "1", features = ["full"] }
prost = "0.13.5"

[build-dependencies]
tonic-build = "0.13.0"
